// GENERATED by scripts/vrc-diorama/codegen.py from register_schema.toml -- DO NOT EDIT.
//
// Compile-time register constants for the UdonSharp battle-diorama decoder.
namespace LegaiaDiorama
{
    public static class Registers
    {
        public const int SchemaVersion = 1;
        public const int MetaChannel = 15;

        // Meta-channel registers.
        public const int MetaSchemaVersion = 0;
        public const int MetaSessionFlags = 1;
        public const int MetaHeartbeat = 2;
        public const int MetaGameMode = 3;
        public const int MetaRegionIdHi = 4;
        public const int MetaRegionIdLo = 5;
        public const int MetaBattlePhase = 6;
        public const int MetaRefreshMarker = 7;
        public const int MetaCommit = 127;

        // Per-slot registers (party + enemy channels).
        public const int SlotFlags = 0;
        public const int SlotIdHi = 1;
        public const int SlotIdLo = 2;
        public const int SlotActionId = 3;
        public const int SlotHpHi = 4;
        public const int SlotHpLo = 5;
        public const int SlotMaxhpHi = 6;
        public const int SlotMaxhpLo = 7;
        public const int SlotStatus = 8;
        public const int SlotTargetSlot = 9;
        public const int SlotCommit = 127;

        // Channel layout.
        public static readonly int[] PartyChannels = { 0, 1, 2 };
        public static readonly int[] EnemyChannels = { 3, 4, 5, 6, 7 };

        // Slot flag-bit positions.
        public const int FlagPresent = 0;
        public const int FlagDead = 1;
        public const int FlagActing = 2;
        public const int FlagTargeted = 3;

        // Status-effect bit positions.
        public const int StatusConfuse = 0;

        // Battle-phase values.
        public const int PhaseNone = 0;
        public const int PhaseIntro = 1;
        public const int PhaseActive = 2;
        public const int PhaseVictory = 3;
        public const int PhaseDefeat = 4;

        public const int TargetNone = 127;
    }
}
