# @category Legaia
# @runtime Jython
#
# Dumps the program's defined data-symbol table to /scripts/funcs/globals_<program>.txt
# in the same header format that scripts/pcsx-redux/build-symbols.py already
# parses. One symbol per line:
#
#     == _DAT_8007bcd0 8007bcd0 (len=4) ==
#     == DAT_8007078c 8007078c (len=448) ==
#
# Sister script of dump_funcs.py - dump_funcs.py emits FUN_* entries via
# `(entry=ADDR)` headers; this one emits global data labels via the
# `(len=N)` header form. build-symbols.py merges both into symbols.json/
# symbols.lua so probes can resolve DAT_* names at runtime.
#
# Coverage targets:
#   * Address ranges 0x80000000..0x80200000 (PSX main RAM mirror) and
#     0x1F800000..0x1F8003FF (scratchpad).
#   * Symbols whose name matches DAT_*, _DAT_*, PTR_DAT_*, or any user-
#     renamed label inside those ranges (we accept anything that's been
#     deliberately named, since renames are deliberate).
#
# Why a sidecar file rather than direct symbols.json:
# The whole pipeline standardises on the funcs/<addr>.txt header format
# so a single tool (build-symbols.py) is authoritative. Adding a parallel
# JSON emitter from Jython would create a second source of truth.
#
# Run inside the existing Ghidra docker compose:
#   docker compose exec ghidra /ghidra/support/analyzeHeadless /projects legaia \
#       -process SCUS_942.54 -noanalysis -postScript /scripts/dump_globals.py
# Then on the host:
#   python3 scripts/pcsx-redux/build-symbols.py
#
# Overlay programs can be run through the same script in turn; each
# program's defined globals land in its own globals_<program>.txt so
# they don't clobber one another.

import os
import re

OUT_DIR = "/scripts/funcs"
try:
    os.makedirs(OUT_DIR)
except OSError:
    pass

# Accept any symbol whose name starts with one of these prefixes OR is a
# user-renamed label inside a known data range. The default prefix list
# covers Ghidra's auto-generated DAT_*/PTR_DAT_*/PTR_* family.
AUTO_PREFIXES = ("DAT_", "_DAT_", "PTR_DAT_", "PTR_", "FLOAT_")

# Skip Ghidra-internal labels and the placeholder dummies.
SKIP_PREFIXES = ("Switch", "case_", "loop_", "LAB_", "switchD_", "caseD_",
                 "default_", "EXTERNAL", "OFF_")

# Address ranges that matter to probes. Anything outside these is junk
# (zero-page noise, IO register space we don't care about, etc).
RAM_RANGES = (
    (0x80000000, 0x80200000),  # main RAM (mirrored)
    (0xA0000000, 0xA0200000),  # KSEG1 mirror (just in case)
    (0x1F800000, 0x1F800400),  # scratchpad
)


def in_ram_ranges(addr):
    a = addr.getOffset() & 0xFFFFFFFF
    for lo, hi in RAM_RANGES:
        if lo <= a < hi:
            return True
    return False


def starts_with_any(s, prefixes):
    for p in prefixes:
        if s.startswith(p):
            return True
    return False


def length_for(addr):
    """Best-effort byte length for a data symbol at addr.

    Use the defined Data object's getLength() when one exists; fall back
    to 4 (the most common DAT_* slot size for the table-of-pointers
    pattern this codebase actually uses).
    """
    data = listing.getDataAt(addr)
    if data is not None:
        try:
            return int(data.getLength())
        except Exception:
            pass
    return 4


prog = currentProgram
listing = prog.getListing()
symtab = prog.getSymbolTable()

prog_name = prog.getName()
out_path = os.path.join(OUT_DIR, "globals_" + prog_name + ".txt")

count = 0
skipped = 0
with open(out_path, "w") as fh:
    fh.write("== globals dump: program={} ==\n".format(prog_name))
    fh.write("# auto-generated by ghidra/scripts/dump_globals.py\n")
    fh.write("# format: == NAME ADDR_HEX (len=N) == per the build-symbols.py grammar\n\n")

    syms = symtab.getDefinedSymbols()
    seen = set()  # (name, addr_hex) tuples; Ghidra can return duplicates from multiple namespaces
    for s in syms:
        name = s.getName()
        addr = s.getAddress()
        if addr is None:
            continue
        if not in_ram_ranges(addr):
            skipped += 1
            continue
        if starts_with_any(name, SKIP_PREFIXES):
            skipped += 1
            continue
        # Accept if it matches an auto-prefix OR if it's been user-renamed
        # (user renames are valuable - they're hand-curated labels).
        is_auto = starts_with_any(name, AUTO_PREFIXES)
        is_user_label = (s.getSource() is not None and
                         str(s.getSource()) == "USER_DEFINED")
        if not (is_auto or is_user_label):
            skipped += 1
            continue

        addr_hex = "{:08x}".format(addr.getOffset() & 0xFFFFFFFF)
        key = (name, addr_hex)
        if key in seen:
            continue
        seen.add(key)

        n = length_for(addr)
        fh.write("== {} {} (len={}) ==\n".format(name, addr_hex, n))
        count += 1

print("wrote {} symbols ({} skipped) to {}".format(count, skipped, out_path))
