[package]
name = "legaia-arts-patch"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "legaia_arts_patch"
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
legaia-art.workspace = true
legaia-asset.workspace = true
legaia-code-hooks.workspace = true
legaia-disc-patch.workspace = true
legaia-iso.workspace = true
legaia-lzs.workspace = true
