[package]
name = "legaia-engine-minigame-scenes"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "legaia_engine_minigame_scenes"
path = "src/lib.rs"

[dependencies]
legaia-asset.workspace = true
legaia-tim.workspace = true
legaia-tmd.workspace = true
legaia-engine-battle.workspace = true
legaia-engine-field.workspace = true
legaia-engine-menus.workspace = true
legaia-engine-minigames.workspace = true
legaia-engine-system.workspace = true
legaia-engine-vm.workspace = true
