[package]
name = "legaia-extract"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "legaia-extract"
path = "src/bin/legaia-extract.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
rayon.workspace = true
serde_json.workspace = true
sha2.workspace = true
legaia-iso.workspace = true
legaia-prot.workspace = true
legaia-asset.workspace = true
legaia-lzs.workspace = true
legaia-tim.workspace = true
legaia-tmd.workspace = true
legaia-xa.workspace = true
legaia-font.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true
