// Editor-side test tools for the casino slot machine.
//
// `Legaia > Verify Slot Rules` replays the committed rules-parity fixture
// (slot-verify.json, generated by the repo's
// crates/engine-core/tests/slot_verify_fixture.rs) against the ACTUAL
// LegaiaSlotMachine UdonSharp class - the proxy is a plain MonoBehaviour in
// the editor, so its private rules methods can be driven directly through
// reflection, with no Udon runtime and no VRC networking. Every per-spin
// field (feature mode, stop rows, claimed values, payout, net take, balance)
// is diffed against the engine kernel's output, which catches exactly the
// silent failure mode of a hand translation: an RNG fold, a `%`, or an
// int-width slip that compiles fine and drifts quietly.
//
// `Legaia > Slot Screen Snapshot` films the machine's on-cabinet screen
// composition head-on from the player's side and saves a PNG - a one-click
// visual check of framing, the mirror, and the reel drum against the
// site's minigames page, without entering play mode.

using System.Collections.Generic;
using System.IO;
using System.Reflection;
using UnityEditor;
using UnityEngine;

namespace LegaiaWorld
{
    public static class LegaiaSlotTools
    {
        const string FIXTURE_PATH = "Assets/LegaiaWorld/Editor/slot-verify.json";
        const string SNAPSHOT_PATH = "Assets/LegaiaGenerated/slot-machine/slot_screen_snapshot.png";
        // Retail's entry seed (must match LegaiaSlotMachine.ENTRY_LCG_SEED).
        const int ENTRY_LCG_SEED = 0x6C0A2AF0;

        static readonly BindingFlags ANY =
            BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public;

        // --- rules parity --------------------------------------------------

        [MenuItem("Legaia/Verify Slot Rules")]
        static void VerifyRules()
        {
            if (!File.Exists(FIXTURE_PATH))
            {
                EditorUtility.DisplayDialog("Legaia slot verify",
                    "Fixture not found:\n" + FIXTURE_PATH +
                    "\n\nSync the kit (it is generated by the repo's " +
                    "slot_verify_fixture.rs test).", "OK");
                return;
            }
            object fixture = MiniJson.Parse(File.ReadAllText(FIXTURE_PATH));
            var payouts = ToIntArray(MiniJson.AsList(MiniJson.Get(fixture, "payouts")));
            var traces = MiniJson.AsList(MiniJson.Get(fixture, "traces"));
            if (payouts == null || traces == null)
            {
                Debug.LogError("[Legaia] slot-verify.json did not parse.");
                return;
            }

            var errors = new List<string>();
            int spinsRun = 0;
            foreach (var trace in traces)
                spinsRun += VerifyTrace(trace, payouts, errors);

            if (errors.Count == 0)
            {
                string msg = "Slot rules verified: " + traces.Count + " traces, " +
                    spinsRun + " spins, every field matches the engine kernel.";
                Debug.Log("[Legaia] " + msg);
                EditorUtility.DisplayDialog("Legaia slot verify", msg, "OK");
            }
            else
            {
                foreach (var e in errors)
                    Debug.LogError("[Legaia] slot verify: " + e);
                EditorUtility.DisplayDialog("Legaia slot verify",
                    errors.Count + " mismatch(es) against the engine kernel - " +
                    "see the Console. The C# rules port has drifted (or the " +
                    "fixture is stale - regenerate it with the repo's " +
                    "slot_verify_fixture.rs bless run).", "OK");
            }
        }

        static int VerifyTrace(object trace, int[] payouts, List<string> errors)
        {
            string name = MiniJson.AsStr(MiniJson.Get(trace, "name")) ?? "?";
            // AsNum (double), not GetNum (float): the retail seed does not
            // fit a float mantissa and would round to a different stream.
            int seed = (int)MiniJson.AsNum(MiniJson.Get(trace, "seed"));
            int spins = (int)MiniJson.AsNum(MiniJson.Get(trace, "spins"));
            int startBalance = (int)MiniJson.AsNum(MiniJson.Get(trace, "start_balance"));

            var go = new GameObject("~legaia-slot-verify");
            go.hideFlags = HideFlags.HideAndDontSave;
            try
            {
                var m = go.AddComponent<LegaiaSlotMachine>();
                m.suppressSerialization = true;
                m.freePlayRefill = false;
                m.autoCollect = false;
                m.payoutTable = payouts;
                Set(m, "isLocalOwner", true);
                Set(m, "syncBalance", startBalance);
                Call(m, "BuildStrips", seed);

                CompareStrips(name, m, "symbolStrip",
                    MiniJson.AsList(MiniJson.Get(trace, "symbol_strips")), errors);
                CompareStrips(name, m, "bonusStrip",
                    MiniJson.AsList(MiniJson.Get(trace, "bonus_strips")), errors);

                var results = MiniJson.AsList(MiniJson.Get(trace, "results"));
                for (int spin = 0; spin < spins; spin++)
                {
                    Call(m, "TrySpin");
                    int mode = GetInt(m, "syncFeatureMode");
                    int guard = 200;
                    while (GetInt(m, "syncPhase") == 2 && guard-- > 0)
                        Call(m, "Tick");
                    for (int reel = 0; reel < 3; reel++)
                    {
                        int gap = reel == 0 ? (spin * 7 + 3) % 11
                            : reel == 1 ? (spin * 5 + 2) % 13
                            : (spin * 3 + 1) % 7;
                        for (int t = 0; t < gap; t++)
                            Call(m, "Tick");
                        Call(m, "StopReel", reel);
                    }
                    object want = results != null && spin < results.Count ? results[spin] : null;
                    string at = name + " spin " + spin;
                    CheckInt(at, "mode", mode, want, errors);
                    var claimed = (int[])Get(m, "claimed");
                    var wantRows = ToIntArray(MiniJson.AsList(MiniJson.Get(want, "rows")));
                    var wantClaimed = ToIntArray(MiniJson.AsList(MiniJson.Get(want, "claimed")));
                    int[] rows =
                    {
                        GetInt(m, "syncStopRow0"),
                        GetInt(m, "syncStopRow1"),
                        GetInt(m, "syncStopRow2"),
                    };
                    for (int r = 0; r < 3; r++)
                    {
                        if (wantRows != null && rows[r] != wantRows[r])
                            errors.Add(at + " reel " + r + " row: got " + rows[r] +
                                " want " + wantRows[r]);
                        if (wantClaimed != null && claimed[r] != wantClaimed[r])
                            errors.Add(at + " reel " + r + " claimed: got " + claimed[r] +
                                " want " + wantClaimed[r]);
                    }
                    CheckInt(at, "line", GetInt(m, "syncWinLine"), want, errors);
                    CheckInt(at, "symbol", GetInt(m, "syncWinSymbol"), want, errors);
                    CheckInt(at, "payout", GetInt(m, "syncPayout"), want, errors);
                    CheckInt(at, "net", GetInt(m, "syncNetTake"), want, errors);
                    CheckInt(at, "bonus", GetInt(m, "syncBonusSpins"), want, errors);
                    CheckInt(at, "mode_after", GetInt(m, "syncFeatureMode"), want, errors);
                    Call(m, "Collect");
                    CheckInt(at, "balance", GetInt(m, "syncBalance"), want, errors);
                    if (errors.Count > 40)
                    {
                        errors.Add(name + ": too many mismatches, stopping this trace.");
                        return spin + 1;
                    }
                }
                return spins;
            }
            finally
            {
                Object.DestroyImmediate(go);
            }
        }

        static void CompareStrips(string name, LegaiaSlotMachine m, string field,
            List<object> want, List<string> errors)
        {
            var got = (int[])Get(m, field);
            for (int reel = 0; want != null && reel < 3 && reel < want.Count; reel++)
            {
                var rowVals = ToIntArray(MiniJson.AsList(want[reel]));
                for (int row = 0; rowVals != null && row < 20; row++)
                    if (got[reel * 20 + row] != rowVals[row])
                        errors.Add(name + " " + field + " reel " + reel + " row " + row +
                            ": got " + got[reel * 20 + row] + " want " + rowVals[row]);
            }
        }

        static void CheckInt(string at, string key, int got, object want, List<string> errors)
        {
            if (want == null)
                return;
            // AsNum (double) so large figures survive; sentinel outside every
            // legitimate field range guards a malformed fixture.
            int expected = (int)MiniJson.AsNum(MiniJson.Get(want, key), -8888888.0);
            if (got != expected)
                errors.Add(at + " " + key + ": got " + got + " want " + expected);
        }

        // --- screen snapshot ------------------------------------------------

        [MenuItem("Legaia/Slot Screen Snapshot")]
        static void Snapshot()
        {
            var machine = Object.FindObjectOfType<LegaiaSlotMachine>();
            if (machine == null)
            {
                EditorUtility.DisplayDialog("Legaia slot snapshot",
                    "No LegaiaSlotMachine in the scene - build one first " +
                    "(Legaia > Build Slot Machine...).", "OK");
                return;
            }
            if (!Application.isPlaying)
            {
                // Pose a real frame in edit mode: seed the strips and run the
                // machine's own visual pass, so the snapshot shows the actual
                // retail-seed drum, furniture and marquee (Start() never ran).
                Call(machine, "BuildEdgeTables");
                Call(machine, "BakeShadeVectors");
                Call(machine, "BuildStrips", ENTRY_LCG_SEED);
                Call(machine, "ForceRedraw");
                Call(machine, "ApplyReelVisuals");
                Call(machine, "RefreshFurniture");
                Call(machine, "RefreshMarquee");
                Call(machine, "UpdateHud");
                Debug.Log("[Legaia] edit-mode snapshot posed the reels in the " +
                    "scene; rebuild the machine to reset the preview pose.");
            }

            // Frame the composition head-on from the player's side: the
            // machine root's +z faces the player, so the camera sits in
            // front looking back. What it films IS what a player sees -
            // no flip, the composition root carries the one mirror.
            var bounds = new Bounds();
            bool hasBounds = false;
            foreach (var r in machine.GetComponentsInChildren<Renderer>())
            {
                if (!r.gameObject.activeInHierarchy)
                    continue;
                if (!hasBounds) { bounds = r.bounds; hasBounds = true; }
                else bounds.Encapsulate(r.bounds);
            }
            if (!hasBounds)
            {
                EditorUtility.DisplayDialog("Legaia slot snapshot",
                    "The machine has no active renderers - rebuild it first.", "OK");
                return;
            }

            var camGo = new GameObject("legaia_snapshot_camera");
            try
            {
                Vector3 fwd = machine.transform.forward;
                camGo.transform.position =
                    bounds.center + fwd * (bounds.extents.magnitude + 1f);
                camGo.transform.rotation =
                    Quaternion.LookRotation(-fwd, machine.transform.up);
                var cam = camGo.AddComponent<Camera>();
                cam.orthographic = true;
                float hw = AbsDot(bounds.extents, camGo.transform.right);
                float hh = AbsDot(bounds.extents, camGo.transform.up);
                cam.orthographicSize = Mathf.Max(hh, hw * 0.75f); // 4:3 frame
                cam.nearClipPlane = 0.01f;
                cam.farClipPlane = bounds.extents.magnitude * 2f + 2f;
                cam.clearFlags = CameraClearFlags.SolidColor;
                cam.backgroundColor = Color.black;

                var rt = RenderTexture.GetTemporary(640, 480, 16);
                cam.targetTexture = rt;
                var prevActive = RenderTexture.active;
                cam.Render();
                RenderTexture.active = rt;
                var tex = new Texture2D(rt.width, rt.height, TextureFormat.RGBA32, false);
                tex.ReadPixels(new Rect(0, 0, rt.width, rt.height), 0, 0);
                tex.Apply();
                RenderTexture.active = prevActive;
                cam.targetTexture = null;
                RenderTexture.ReleaseTemporary(rt);

                Directory.CreateDirectory(Path.GetDirectoryName(SNAPSHOT_PATH));
                File.WriteAllBytes(SNAPSHOT_PATH, tex.EncodeToPNG());
                Object.DestroyImmediate(tex);
            }
            finally
            {
                Object.DestroyImmediate(camGo);
            }
            AssetDatabase.ImportAsset(SNAPSHOT_PATH);
            var asset = AssetDatabase.LoadAssetAtPath<Texture2D>(SNAPSHOT_PATH);
            if (asset != null)
                EditorGUIUtility.PingObject(asset);
            Debug.Log("[Legaia] slot screen snapshot -> " + SNAPSHOT_PATH +
                " (compare against the site minigames page render).");
        }

        /// Half-extent of an AABB along an arbitrary world axis.
        static float AbsDot(Vector3 extents, Vector3 axis)
        {
            return extents.x * Mathf.Abs(axis.x)
                 + extents.y * Mathf.Abs(axis.y)
                 + extents.z * Mathf.Abs(axis.z);
        }

        // --- reflection over the U# proxy -----------------------------------

        static object Get(LegaiaSlotMachine m, string field)
        {
            return typeof(LegaiaSlotMachine).GetField(field, ANY).GetValue(m);
        }

        static int GetInt(LegaiaSlotMachine m, string field)
        {
            return (int)Get(m, field);
        }

        static void Set(LegaiaSlotMachine m, string field, object value)
        {
            typeof(LegaiaSlotMachine).GetField(field, ANY).SetValue(m, value);
        }

        static void Call(LegaiaSlotMachine m, string method, params object[] args)
        {
            typeof(LegaiaSlotMachine).GetMethod(method, ANY).Invoke(m, args);
        }

        static int[] ToIntArray(List<object> list)
        {
            if (list == null)
                return null;
            var arr = new int[list.Count];
            for (int i = 0; i < list.Count; i++)
                arr[i] = (int)MiniJson.AsNum(list[i]);
            return arr;
        }
    }
}
