//! Phase K2 - schema fixture for `SaveFile` ↔ retail SC block.
//!
//! Pins the byte-level layout of both the engine's `LGSF v2` save buffer
//! and the retail PSX `SC` save block by snapshotting the writer output
//! of a deterministic synthetic [`SaveFile`] into golden fixture files
//! under `tests/fixtures/`. Any change to either writer drifts the
//! generated bytes and breaks this test loudly. The companion
//! `tests/fixtures/schema.md` documents the field map and the
//! engine-only fields that round-trip through LGSF v2 but have no SC
//! representation.
//!
//! To intentionally regenerate the fixtures after a writer change:
//!
//! ```text
//! LEGAIA_UPDATE_FIXTURES=1 cargo test -p legaia-save --test schema_fixture
//! ```
//!
//! No Sony bytes appear in this test - the synthetic builder writes
//! only sentinel values through the public API.

use legaia_save::{
    BLOCK_SIZE, CharSaveExt, CharacterRecord, HpMpSp, Party, RETAIL_STORY_FLAGS_SIZE,
    SAVE_BLOCK_MAGIC, SAVE_FILE_EXT_MAGIC, SAVE_FILE_EXT3_MAGIC, SAVE_FILE_MAGIC,
    SAVE_FILE_VERSION, SaveExt, SaveExtV2, SaveFile, SavedChainRecord, read_retail_inventory,
    read_retail_story_flags,
};

const LGSF_FIXTURE: &str = "tests/fixtures/schema_synthetic.lgsf.bin";
const SC_FIXTURE: &str = "tests/fixtures/schema_synthetic.sc.bin";

/// Deterministic synthetic save covering every `SaveFile` field. The
/// builder is the single source of truth for what the golden fixtures
/// encode - regenerating the fixtures with `LEGAIA_UPDATE_FIXTURES=1`
/// just snapshots whatever this function returns.
fn build_synthetic_save() -> SaveFile {
    let mut party = Party { members: vec![] };
    for i in 0..3u8 {
        let mut rec = CharacterRecord::zeroed();
        // raw[0] sentinel keeps the record from looking "empty" to the
        // SC reader (which stops at the first all-zero slot).
        rec.raw[0] = (i + 1) * 0x11;
        rec.set_level(10 + i);
        rec.set_cumulative_xp(500 + u16::from(i) * 50);
        rec.set_hp_mp_sp(HpMpSp {
            hp_cur: 100 + u16::from(i) * 10,
            hp_max: 100 + u16::from(i) * 10,
            mp_cur: 50,
            mp_max: 50,
            sp_cur: 0,
            sp_max: 0,
        });
        rec.set_stat_cap(0x3E7);
        party.members.push(rec);
    }

    // Retail-shaped 512-byte story-flag bitmap with a deterministic
    // sweep pattern, so any off-by-one in the SC writer surfaces in the
    // diff between the golden bytes and the regenerated output.
    let mut story_flag_bits = vec![0u8; RETAIL_STORY_FLAGS_SIZE];
    for (i, b) in story_flag_bits.iter_mut().enumerate() {
        *b = (i as u8).wrapping_mul(0x33);
    }
    let story_flags = u32::from_le_bytes([
        story_flag_bits[0],
        story_flag_bits[1],
        story_flag_bits[2],
        story_flag_bits[3],
    ]);

    SaveFile {
        party,
        ext: SaveExt {
            story_flags,
            story_flag_bits,
            money: 1234,
            inventory: vec![(0x05, 9), (0x10, 1), (0x33, 64)],
        },
        ext_v2: SaveExtV2 {
            play_time_seconds: 7200,
            active_party: vec![0, 1, 2],
            per_char: vec![(
                0,
                CharSaveExt {
                    learned_arts_mask: 0x0000_00FF,
                    spells: vec![0x10, 0x11, 0x20],
                    seru_captures: vec![(1, 50)],
                    active_chains: [[1, 2, 3, 4], [0; 4], [0; 4], [0; 4]],
                },
            )],
            saved_chains: vec![SavedChainRecord {
                char_slot: 0,
                name: "K2_FIXTURE".into(),
                sequence: vec![1, 2, 3, 4],
            }],
        },
    }
}

fn fixture_path(rel: &str) -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(rel)
}

/// Either compare `actual` against the golden bytes at `rel` or, when
/// `LEGAIA_UPDATE_FIXTURES=1` is set, overwrite the golden file with
/// `actual` so the next run passes.
fn assert_golden(rel: &str, actual: &[u8]) {
    let path = fixture_path(rel);
    if std::env::var_os("LEGAIA_UPDATE_FIXTURES").is_some() {
        std::fs::write(&path, actual)
            .unwrap_or_else(|e| panic!("write fixture {}: {e}", path.display()));
        eprintln!(
            "[fixture] updated {} ({} bytes)",
            path.display(),
            actual.len()
        );
        return;
    }
    let expected = std::fs::read(&path).unwrap_or_else(|e| {
        panic!(
            "read fixture {} (set LEGAIA_UPDATE_FIXTURES=1 to regenerate): {e}",
            path.display()
        )
    });
    if actual != expected.as_slice() {
        let first_diff = actual
            .iter()
            .zip(expected.iter())
            .position(|(a, b)| a != b)
            .unwrap_or(expected.len().min(actual.len()));
        panic!(
            "fixture {} diverged: lengths actual={} expected={}, first diff at byte {:#x} \
             actual={:#04x} expected={:#04x}. \
             If the change is intentional, rerun with LEGAIA_UPDATE_FIXTURES=1.",
            path.display(),
            actual.len(),
            expected.len(),
            first_diff,
            actual.get(first_diff).copied().unwrap_or(0),
            expected.get(first_diff).copied().unwrap_or(0),
        );
    }
}

#[test]
fn lgsf_v2_writer_matches_golden_fixture() {
    let save = build_synthetic_save();
    let bytes = save.write();

    // Sanity check the buffer structure before touching the disk: any
    // schema drift that survives writer.write() but corrupts the
    // headers should fail here first with a clearer message.
    assert_eq!(&bytes[..4], &SAVE_FILE_MAGIC, "LGSF magic at offset 0");
    assert_eq!(
        bytes[4], SAVE_FILE_VERSION,
        "writer should emit current LGSF version"
    );
    assert!(
        bytes.windows(4).any(|w| w == SAVE_FILE_EXT_MAGIC),
        "LGSF v2 buffer must contain the LGX2 sentinel"
    );
    assert!(
        bytes.windows(4).any(|w| w == SAVE_FILE_EXT3_MAGIC),
        "LGSF v3 buffer must contain the LGX3 sentinel"
    );

    assert_golden(LGSF_FIXTURE, &bytes);
}

#[test]
fn retail_sc_writer_matches_golden_fixture() {
    let save = build_synthetic_save();
    let mut sc_block = vec![0u8; BLOCK_SIZE];
    save.write_into_retail_sc_block(&mut sc_block)
        .expect("write into retail SC block");

    assert_eq!(&sc_block[..2], &SAVE_BLOCK_MAGIC, "SC magic stamped at +0");
    let bits = read_retail_story_flags(&sc_block).expect("story flags region present");
    assert_eq!(
        bits,
        save.ext.story_flag_bits.as_slice(),
        "story flag bitmap lands at retail offset"
    );
    let inv = read_retail_inventory(&sc_block).expect("inventory region present");
    assert_eq!(
        &inv[..6],
        &[0x05, 9, 0x10, 1, 0x33, 64],
        "inventory pairs land at retail offset"
    );

    assert_golden(SC_FIXTURE, &sc_block);
}

#[test]
fn lgsf_v2_round_trips_struct_identical() {
    // Closing half of the K2 contract: bytes generated by the writer
    // parse back to a struct that compares equal to the original.
    let save = build_synthetic_save();
    let bytes = save.write();
    let parsed = SaveFile::parse(&bytes).expect("LGSF v2 round-trip");
    assert_eq!(parsed, save, "LGSF v2 round-trip preserves every field");
}

#[test]
fn retail_sc_round_trips_only_representable_fields() {
    // The retail SC block has no slot for money, play_time, active_party,
    // per_char ext, or saved_chains, so a round-trip through
    // write_into_retail_sc_block + from_retail_sc_block drops those
    // fields to their defaults. The party records, full story-flag
    // bitmap, and inventory survive byte-exact.
    let save = build_synthetic_save();
    let mut sc_block = vec![0u8; BLOCK_SIZE];
    save.write_into_retail_sc_block(&mut sc_block)
        .expect("write into retail SC block");

    let parsed = SaveFile::from_retail_sc_block(&sc_block, save.party.members.len())
        .expect("read back retail SC block");

    // Party records: byte-equal.
    assert_eq!(
        parsed.party.members.len(),
        save.party.members.len(),
        "all record slots round-trip"
    );
    for (i, (a, b)) in parsed
        .party
        .members
        .iter()
        .zip(save.party.members.iter())
        .enumerate()
    {
        assert_eq!(a.raw, b.raw, "char record {i} round-trips byte-exact");
    }

    // Story-flag bitmap: byte-equal full 512 bytes.
    assert_eq!(
        parsed.ext.story_flag_bits, save.ext.story_flag_bits,
        "story flag bitmap byte-equal"
    );
    // Scratchpad story_flags u32 is derived from the first 4 bitmap
    // bytes on the SC read path, so the two must agree exactly.
    assert_eq!(
        parsed.ext.story_flags, save.ext.story_flags,
        "scratchpad story_flags derived from bitmap bytes"
    );

    // Inventory: the SC reader drops `(0, 0)` empties so the compact
    // engine inventory survives in order.
    assert_eq!(
        parsed.ext.inventory, save.ext.inventory,
        "inventory pairs survive in order"
    );

    // Engine-only fields drop to defaults through the SC layout.
    assert_eq!(parsed.ext.money, 0, "money is engine-only");
    assert_eq!(parsed.ext_v2, SaveExtV2::default(), "v2 ext is engine-only");
}
