// Wind-swayed grass blades for the builder's procedural ground foliage.
// The blades are bare vertex-coloured triangles (no texture, generated by
// LegaiaRealism.ScatterGrass - no game data): colour carries the tint
// sampled from the terrain, alpha carries the sway weight (0 at the root,
// 1 at the tip) so only tips move. World-position phase keeps neighbouring
// tufts out of sync without any per-instance data.
Shader "Legaia/Grass Wind"
{
    Properties
    {
        _WindStrength ("Wind strength (m)", Range(0, 0.3)) = 0.06
        _WindSpeed ("Wind speed", Range(0, 8)) = 1.6
        _Glossiness ("Smoothness", Range(0,1)) = 0.05
    }
    SubShader
    {
        Tags { "RenderType"="Opaque" "Queue"="Geometry" }
        Cull Off
        LOD 200

        CGPROGRAM
        #pragma surface surf Standard vertex:vert addshadow
        #pragma target 3.0

        half _WindStrength;
        half _WindSpeed;
        half _Glossiness;

        struct Input
        {
            float4 color : COLOR;
        };

        void vert (inout appdata_full v)
        {
            float3 wp = mul(unity_ObjectToWorld, v.vertex).xyz;
            float w = v.color.a * _WindStrength;
            float t = _Time.y * _WindSpeed;
            float s = sin(t + wp.x * 0.7 + wp.z * 0.5)
                    + 0.4 * sin(t * 2.3 + wp.z * 1.3);
            v.vertex.x += s * w;
            v.vertex.z += cos(t * 0.9 + wp.x * 0.8) * 0.6 * w;
        }

        void surf (Input IN, inout SurfaceOutputStandard o)
        {
            o.Albedo = IN.color.rgb;
            o.Metallic = 0;
            o.Smoothness = _Glossiness;
        }
        ENDCG
    }
    FallBack "Diffuse"
}
