#!/usr/bin/env python3
"""Codegen for the battle-diorama MIDI register protocol.

Reads `register_schema.toml` (the single source of truth) and emits both sides
of the wire so they cannot drift:

  generated/registers.lua  -- a pure data table the Lua MIDI encoder requires.
  world-project/Assets/LegaiaDiorama/Registers.cs -- UdonSharp decoder constants.

Usage:
  codegen.py            regenerate both files in place
  codegen.py --check    regenerate to memory and fail if the committed files
                        differ (CI / pre-commit drift gate)

No Sony bytes: this is protocol structure only.
"""

import argparse
import sys
import tomllib
from pathlib import Path

HERE = Path(__file__).resolve().parent
SCHEMA = HERE / "register_schema.toml"
GEN = HERE / "generated"
LUA_OUT = GEN / "registers.lua"
# The C# constants live in the Unity world project's Assets tree (their real,
# Unity-needed home); their .cs.meta GUID persists across regen (gen-meta.py).
CS_OUT = HERE / "world-project" / "Assets" / "LegaiaDiorama" / "Registers.cs"

BANNER = "GENERATED by scripts/vrc-diorama/codegen.py from register_schema.toml -- DO NOT EDIT."


def load_schema() -> dict:
    with open(SCHEMA, "rb") as fh:
        return tomllib.load(fh)


def _regs(d: dict) -> list[tuple[str, dict]]:
    """Registers as (name, spec) pairs sorted by cc."""
    return sorted(d.items(), key=lambda kv: kv[1]["cc"])


def gen_lua(s: dict) -> str:
    L = []
    a = L.append
    a("-- " + BANNER)
    a("--")
    a("-- Returns the register map the Lua MIDI encoder (midi_encoder.lua) uses.")
    a("-- Values are MIDI cc numbers unless noted. Wide registers list {hi, lo}.")
    a("")
    a("local M = {}")
    a("")
    a(f"M.SCHEMA_VERSION = {s['schema_version']}")
    a(f"M.META_CHANNEL = {s['meta']['channel']}")
    a(f"M.PARTY_CHANNELS = {{ {', '.join(str(c) for c in s['party']['channels'])} }}")
    a(f"M.ENEMY_CHANNELS = {{ {', '.join(str(c) for c in s['enemy']['channels'])} }}")
    a("")

    def emit_regs(name: str, regs: dict):
        a(f"M.{name} = {{")
        for rname, spec in _regs(regs):
            if spec.get("wide"):
                a(f"  {rname} = {{ hi = {spec['cc']}, lo = {spec['cc'] + 1}, wide = true }},")
            else:
                a(f"  {rname} = {{ cc = {spec['cc']} }},")
        a("}")
        a("")

    emit_regs("META", s["meta"]["registers"])
    emit_regs("SLOT", s["slot"]["registers"])

    def emit_map(name: str, m: dict):
        a(f"M.{name} = {{")
        for k, v in m.items():
            a(f"  {k} = {v},")
        a("}")
        a("")

    emit_map("FLAG_BITS", s["slot"]["flag_bits"])
    emit_map("STATUS_BITS", s["slot"]["status_bits"])
    emit_map("BATTLE_PHASE", s["battle_phase_values"])
    emit_map("CONSTANTS", s["constants"])

    a("return M")
    a("")
    return "\n".join(L)


def gen_cs(s: dict) -> str:
    L = []
    a = L.append
    a("// " + BANNER)
    a("//")
    a("// Compile-time register constants for the UdonSharp battle-diorama decoder.")
    a("namespace LegaiaDiorama")
    a("{")
    a("    public static class Registers")
    a("    {")
    a(f"        public const int SchemaVersion = {s['schema_version']};")
    a(f"        public const int MetaChannel = {s['meta']['channel']};")
    a("")
    a("        // Meta-channel registers.")
    for rname, spec in _regs(s["meta"]["registers"]):
        cname = "Meta" + "".join(p.capitalize() for p in rname.split("_"))
        if spec.get("wide"):
            a(f"        public const int {cname}Hi = {spec['cc']};")
            a(f"        public const int {cname}Lo = {spec['cc'] + 1};")
        else:
            a(f"        public const int {cname} = {spec['cc']};")
    a("")
    a("        // Per-slot registers (party + enemy channels).")
    for rname, spec in _regs(s["slot"]["registers"]):
        cname = "Slot" + "".join(p.capitalize() for p in rname.split("_"))
        if spec.get("wide"):
            a(f"        public const int {cname}Hi = {spec['cc']};")
            a(f"        public const int {cname}Lo = {spec['cc'] + 1};")
        else:
            a(f"        public const int {cname} = {spec['cc']};")
    a("")
    a("        // Channel layout.")
    a(f"        public static readonly int[] PartyChannels = {{ {', '.join(str(c) for c in s['party']['channels'])} }};")
    a(f"        public static readonly int[] EnemyChannels = {{ {', '.join(str(c) for c in s['enemy']['channels'])} }};")
    a("")
    a("        // Slot flag-bit positions.")
    for k, v in s["slot"]["flag_bits"].items():
        a(f"        public const int Flag{k.capitalize()} = {v};")
    a("")
    a("        // Status-effect bit positions.")
    for k, v in s["slot"]["status_bits"].items():
        a(f"        public const int Status{k.capitalize()} = {v};")
    a("")
    a("        // Battle-phase values.")
    for k, v in s["battle_phase_values"].items():
        a(f"        public const int Phase{k.capitalize()} = {v};")
    a("")
    a(f"        public const int TargetNone = {s['constants']['target_none']};")
    a("    }")
    a("}")
    a("")
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="fail if committed generated files differ from a fresh render")
    args = ap.parse_args()

    s = load_schema()
    lua = gen_lua(s)
    cs = gen_cs(s)

    if args.check:
        bad = []
        for path, want in ((LUA_OUT, lua), (CS_OUT, cs)):
            have = path.read_text() if path.exists() else None
            if have != want:
                bad.append(path.name)
        if bad:
            print(f"[codegen] DRIFT: {', '.join(bad)} out of date -- run scripts/vrc-diorama/codegen.py",
                  file=sys.stderr)
            return 1
        print("[codegen] OK -- generated files match the schema")
        return 0

    GEN.mkdir(exist_ok=True)
    LUA_OUT.write_text(lua)
    CS_OUT.write_text(cs)
    print(f"[codegen] wrote {LUA_OUT.relative_to(HERE.parent.parent)}")
    print(f"[codegen] wrote {CS_OUT.relative_to(HERE.parent.parent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
